# Generated by Django 2.2.12 on 2020-04-10 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(help_text='Nombre del tag', max_length=40, verbose_name='Nombre del tag')),
                ('code', models.CharField(db_index=True, help_text='Código del tag', max_length=20, primary_key=True, serialize=False, verbose_name='Código del tag')),
                ('active', models.BooleanField(db_index=True, default=True, null=True)),
                ('icon', models.CharField(help_text='Ícono Font Awesome, ejemplo: fa fa-star', max_length=30, null=True, verbose_name='Ícono del tag')),
                ('color', models.CharField(help_text='Color hexadecimal, ejemplo: #70798C', max_length=7, null=True, verbose_name='Color del tag')),
                ('private', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='helprequest',
            name='tag_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Tag'),
        ),
    ]
