# Generated by Django 2.2.12 on 2020-04-09 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='status_id',
            field=models.ForeignKey(default='pendiente', on_delete=django.db.models.deletion.CASCADE, to='core.Status'),
        ),
    ]
